/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2018-12-08 00:10:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import CentreSportif.*;

public final class participants_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("CentreSportif");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>IFT287 - Système de gestion du centre sportif</title>\r\n");
      out.write("\t\t<meta name=\"author\" content=\"Alexandre Beausoleil\">\r\n");
      out.write("\t\t<meta name=\"description\" content=\"Page de gestion des participants\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Required meta tags -->\r\n");
      out.write("\t    <meta charset=\"utf-8\">\r\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <!-- Bootstrap CSS -->\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/navigation.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<h1 class=\"text-center\">Participant</h1>\r\n");
      out.write("\t\t\t<h3 class=\"text-left\">Inscrire un participant</h3>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 pull-left\">\r\n");
      out.write("\t\t\t<form action=\"Participants\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"matricule\">Matricule</label>\r\n");
      out.write("\t\t\t    \t<input class=\"form-control\" type=\"NUMBER\" name=\"matricule\" min=\"1\" value=\"");
      out.print( (request.getAttribute("matricule") != null ? (String)request.getAttribute("matricule") : "") );
      out.write("\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"nom\">Nom</label>\r\n");
      out.write("\t\t\t\t    <input class=\"form-control\" type=\"TEXT\" name=\"nom\" value=\"");
      out.print( (request.getAttribute("nom") != null ? (String)request.getAttribute("nom") : "") );
      out.write("\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"prenom\">Prenom</label>\r\n");
      out.write("\t\t\t\t    <input class=\"form-control\" type=\"TEXT\" name=\"prenom\" value=\"");
      out.print( (request.getAttribute("prenom") != null ? (String)request.getAttribute("prenom") : "") );
      out.write("\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"motDePasse\">Mot de passe</label>\r\n");
      out.write("\t\t\t\t    <input class=\"form-control\" type=\"PASSWORD\" name=\"motDePasse\" value=\"");
      out.print( (request.getAttribute("motDePasse") != null ? (String)request.getAttribute("motDePasse") : "") );
      out.write("\">\r\n");
      out.write("\t\t\t    </div>\t    \t\t\t    \r\n");
      out.write("\t\t\t    <div class=\"row\">\r\n");
      out.write("\t\t\t    \t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"btn btn-primary\" type=\"SUBMIT\" name=\"inscrireParticipant\" value=\"Inscrire le participant\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h3 class=\"text-left\">Supprimer un participant</h3>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 pull-left\">\r\n");
      out.write("\t\t\t<form action=\"Participants\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"matricule\">Matricule</label>\r\n");
      out.write("\t\t\t    \t<select class=\"form-control\" name=\"matricule\">\r\n");
      out.write("\t\t\t\t\t    <option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t    ");
  GestionCentreSportif centreSportifInterro = (GestionCentreSportif) request.getSession().getAttribute("centreSportifInterrogation");  
					    ArrayList<String> matricule = centreSportifInterro.getGestionParticipant().getParticipant().getParticipantsMatricule();
				    	for(String s : matricule) {
				    		
      out.write("<option value=\"");
      out.print( s );
      out.write('"');
      out.write('>');
      out.print( s );
      out.write("</option>");

			    		}
      out.write("\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"row\">\r\n");
      out.write("\t\t\t    \t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"btn btn-primary\" type=\"SUBMIT\" name=\"supprimerParticipant\" value=\"Supprimer le participant\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h3 class=\"text-left\">Inscrire un participant à une équipe</h3>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 pull-left\">\r\n");
      out.write("\t\t\t<form action=\"Participants\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"matricule\">Matricule</label>\r\n");
      out.write("\t\t\t    \t<select class=\"form-control\" name=\"matricule\">\r\n");
      out.write("\t\t\t\t\t    <option value=\"\"></option>   \r\n");
      out.write("  \t\t\t\t\t    ");
for(String s : matricule) {
				    		
      out.write("<option value=\"");
      out.print( s );
      out.write('"');
      out.write('>');
      out.print( s );
      out.write("</option>");

			    		}
      out.write("\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"nomEquipe\">Nom de léquipe</label>\r\n");
      out.write("\t\t\t    \t<select class=\"form-control\" name=\"nomEquipe\">\r\n");
      out.write("\t\t\t\t\t    <option value=\"\"></option>   \r\n");
      out.write("  \t\t\t\t\t    ");
ArrayList<String> equipes = centreSportifInterro.getGestionEquipe().getEquipe().getNomEquipes();
  					    for(String s : equipes) {
				    		
      out.write("<option value=\"");
      out.print( s );
      out.write('"');
      out.write('>');
      out.print( s );
      out.write("</option>");

			    		}
      out.write("\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"row\">\r\n");
      out.write("\t\t\t    \t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"btn btn-primary\" type=\"SUBMIT\" name=\"ajouterJoueur\" value=\"S'inscrire dans cette équipe\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h3 class=\"text-left\">Accepter un participant dans l'équipe</h3>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 pull-left\">\r\n");
      out.write("\t\t\t<form action=\"Participants\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"matricule\">Matricule</label>\r\n");
      out.write("\t\t\t    \t<select class=\"form-control\" name=\"matricule\">\r\n");
      out.write("\t\t\t\t\t    <option value=\"\"></option>   \r\n");
      out.write("  \t\t\t\t\t    ");
 ArrayList<String> matriculeInscrit = centreSportifInterro.getGestionParticipant().getParticipant().getParticipantsInscrit();
  					    for(String s : matriculeInscrit) {
				    		
      out.write("<option value=\"");
      out.print( s );
      out.write('"');
      out.write('>');
      out.print( s );
      out.write("</option>");

			    		}
      out.write("\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"nomEquipe\">Nom de léquipe</label>\r\n");
      out.write("\t\t\t    \t<select class=\"form-control\" name=\"nomEquipe\">\r\n");
      out.write("\t\t\t\t\t    <option value=\"\"></option>   \r\n");
      out.write("  \t\t\t\t\t    ");
for(String s : equipes) {
				    		
      out.write("<option value=\"");
      out.print( s );
      out.write('"');
      out.write('>');
      out.print( s );
      out.write("</option>");

			    		}
      out.write("\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"row\">\r\n");
      out.write("\t\t\t    \t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"btn btn-primary\" type=\"SUBMIT\" name=\"accepterJoueur\" value=\"Accepter le joueur\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h3 class=\"text-left\">Refuser un participant dans l'équipe</h3>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 pull-left\">\r\n");
      out.write("\t\t\t<form action=\"Participants\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"matricule\">Matricule</label>\r\n");
      out.write("\t\t\t    \t<select class=\"form-control\" name=\"matricule\">\r\n");
      out.write("\t\t\t\t\t    <option value=\"\"></option>   \r\n");
      out.write("  \t\t\t\t\t    ");
for(String s : matriculeInscrit) {
				    		
      out.write("<option value=\"");
      out.print( s );
      out.write('"');
      out.write('>');
      out.print( s );
      out.write("</option>");

			    		}
      out.write("\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"nomEquipe\">Nom de léquipe</label>\r\n");
      out.write("\t\t\t    \t<select class=\"form-control\" name=\"nomEquipe\">\r\n");
      out.write("\t\t\t\t\t    <option value=\"\"></option>   \r\n");
      out.write("  \t\t\t\t\t    ");
for(String s : equipes) {
				    		
      out.write("<option value=\"");
      out.print( s );
      out.write('"');
      out.write('>');
      out.print( s );
      out.write("</option>");

			    		}
      out.write("\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"row\">\r\n");
      out.write("\t\t\t    \t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"btn btn-primary\" type=\"SUBMIT\" name=\"refuserJoueur\" value=\"Refuser le joueur\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h3 class=\"text-left\">Supprimer un joueur d'une équipe</h3>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 pull-left\">\r\n");
      out.write("\t\t\t<form action=\"Participants\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"matricule\">Matricule</label>\r\n");
      out.write("\t\t\t    \t<select class=\"form-control\" name=\"matricule\">\r\n");
      out.write("\t\t\t\t\t    <option value=\"\"></option>   \r\n");
      out.write("  \t\t\t\t\t    ");
ArrayList<String> matriculeEquipe = centreSportifInterro.getGestionParticipant().getParticipant().getParticipantsDansEquipe();
  					    for(String s : matriculeEquipe) {
				    		
      out.write("<option value=\"");
      out.print( s );
      out.write('"');
      out.write('>');
      out.print( s );
      out.write("</option>");

			    		}
      out.write("\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t<label for=\"nomEquipe\">Nom de léquipe</label>\r\n");
      out.write("\t\t\t    \t<select class=\"form-control\" name=\"nomEquipe\">\r\n");
      out.write("\t\t\t\t\t    <option value=\"\"></option>   \r\n");
      out.write("  \t\t\t\t\t    ");
for(String s : equipes) {
				    		
      out.write("<option value=\"");
      out.print( s );
      out.write('"');
      out.write('>');
      out.print( s );
      out.write("</option>");

			    		}
      out.write("\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"row\">\r\n");
      out.write("\t\t\t    \t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"btn btn-primary\" type=\"SUBMIT\" name=\"supprimerJoueur\" value=\"Supprimer le joueur de l'équipe\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/messageSucces.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/messageErreur.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
